{ ... }:
{
  programs.kitty = {
    enable = true;

    # 配置本体写在独立文件 kitty.conf，这里只负责读入。
    #
    # 为什么用 extraConfig 而不是 xdg.configFile 覆盖：
    # 模块自身会写 ~/.config/kitty/kitty.conf（内容为"Generated by Home Manager"头 + extraConfig），
    # 若再用 xdg.configFile 设 source 会与模块设的 text 冲突（二者互斥，求值即报错）。
    #
    # 走 extraConfig 的好处：保留模块自带的 onChange，
    # 每次 rebuild 后自动 `pkill -USR1 kitty` 让已运行的窗口热重载配置。
    extraConfig = builtins.readFile ./kitty.conf;
  };
}
